import type { Metadata } from "next";
import {
    Titillium_Web,
} from "next/font/google";
import "./globals.css";
import SpaceBackground from "@/components/UI/SpaceBackground/SpaceBackground";

const font = Titillium_Web({
    subsets: ["latin"],
    weight: ["300", "400", "600", "700", "900"],
});

export const metadata: Metadata = {
    title: "Star Wars",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={font.className}>
                <>
                    <SpaceBackground />
                    {children}
                </>
            </body>
        </html>
    );
}
